pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/kamala127/pharmaflow'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-app .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8081:8080 my-app'
            }
        }
    }
}